name: segment-eval
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=11.8
  - numpy
  - matplotlib
  - pandas
  - tqdm
  - scikit-learn
  - scikit-image
  - pip
  - pip:
    # Installs custom app module
    - -e .
    - opencv-contrib-python
    - pycocotools
    - pysaliency