name: segment-eval
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.8   
  - pytorch
  - numpy
  - matplotlib
  - pandas
  - tqdm
  - scikit-learn
  - scikit-image
  - pip
  - pip:
    # Installs custom app module
    - -e .
    - opencv-contrib-python
    - pycocotools
    - pysaliency